### ISSUE TITLE
Error When NHK Podcast

### ISSUE THREAD

**Issue by NoodlesStamps** [saveweb/preserve-those-podcasts#1]
I get the error when trying to archive NHK podcasts
```
PODCAST RSS :https://www.nhk.or.jp/s-media/news/podcast/list/v1/all.xml
```
```
session: Monkey patch done.
Uploading podcast: c1d47528-b9b7-56f8-94ca-024e06ee690e: NHKラジオニュース
Uploading episode: pod_data/podcasts_audio/c1d47528-b9b7-56f8-94ca-024e06ee690e/58b8a22ec3597df7bd203f0bc744189024f1b25a
2c805c99381ef825a4b591ecd0e817b8_64k.mp3.metadata.json <==
pod_data/podcasts_audio/c1d47528-b9b7-56f8-94ca-024e06ee690e/58b8a22ec3597df7bd203f0bc744189024f1b25a/2c805c99381ef825a4b591ecd0e817b8_64k.mp3.metadat
a.json
entry_guid_sha1_58b8a22ec3597df7bd203f0bc744189024f1b25a.json <==
pod_data/podcasts_audio/c1d47528-b9b7-56f8-94ca-024e06ee690e/58b8a22ec3597df7bd203f0bc744189024f1b25a/entry_guid_sha1_58b8a22ec3597df7bd203f0bc7441890
24f1b25a.json
2c805c99381ef825a4b591ecd0e817b8_64k.mp3 <==
pod_data/podcasts_audio/c1d47528-b9b7-56f8-94ca-024e06ee690e/58b8a22ec3597df7bd203f0bc744189024f1b25a/2c805c99381ef825a4b591ecd0e817b8_64k.mp3
Identifier: "podcast_ep_58b8a22ec3597df7bd203f0bc744189024f1b25a"
Traceback (most recent call last):
  File "/home/jun/.local/bin/podcastsUpload", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jun/.local/share/pipx/venvs/preservethosepod/lib/python3.12/site-packages/preserve_podcasts/uploadPodcasts.py", line 445, in main
    upload_podcasts(args=args, session=session)
  File "/home/jun/.local/share/pipx/venvs/preservethosepod/lib/python3.12/site-packages/preserve_podcasts/uploadPodcasts.py", line 89, in upload_podcasts
    upload_podcast(this_podcast, args=args, session=session)
  File "/home/jun/.local/share/pipx/venvs/preservethosepod/lib/python3.12/site-packages/preserve_podcasts/uploadPodcasts.py", line 107, in upload_podcast
    upload_episode(podcast, ep_audio_dir, args=args, session=session)
  File "/home/jun/.local/share/pipx/venvs/preservethosepod/lib/python3.12/site-packages/preserve_podcasts/uploadPodcasts.py", line 274, in upload_episode
    "link": ep_metadata['link'],
            ~~~~~~~~~~~^^^^^^^^
KeyError: 'link'
session: Undo monkey patch...
```

It worked for these PODCASTRSS 
https://www3.nhk.or.jp/rj/podcast/rss/english.xml

Thank you for creating a great program.

**Comment by yzqzss** [comment]
Is this podcast in danger and needs to be archived immediately?
If not, I'd like to debug it tomorrow, I'm ready for bed now. :)

**Comment by NoodlesStamps** [comment]
Sorry it's late at night, not ASAP things

**Comment by yzqzss** [comment]
Hi, did v1.0.12 solve this issue?

**Comment by NoodlesStamps** [comment]
I apologize for the delayed response, and thank you for fix program and taking your time. It seems the program is functioning properly.
